import asyncio
from pathlib import Path
from ollama_fleet.config import FleetSettings
from ollama_fleet.db.database import Database
from ollama_fleet.orchestrator.orchestrator import Orchestrator
from ollama_fleet.agents.schemas import (
    AgentType,
    PlannerOutput,
    PlannerTask,
    CoderOutput,
    CriticOutput,
    TesterOutput,
)

class CalculatorDummyExecutor:
    def __init__(self, settings=None):
        self.settings = settings
        self.client = None

    async def execute(self, task, agent_type, extra_context=None):
        if agent_type == AgentType.PLANNER:
            planner_task = PlannerTask(
                task_id="build-calculator",
                title="Implement calculator module",
                description="Create a Python calculator module with add, subtract, multiply, divide, and a CLI.",
                agent_type="coder",
                dependencies=[],
                priority=5,
            )
            return PlannerOutput(
                tasks=[planner_task],
                milestones=["calculator-ready"],
                architecture_notes="Single module calculator",
            )

        if agent_type == AgentType.CODER:
            code = '''"""Calculator module generated by orchestrator."""


def add(a, b):
    return a + b


def subtract(a, b):
    return a - b


def multiply(a, b):
    return a * b


def divide(a, b):
    if b == 0:
        raise ValueError('Cannot divide by zero')
    return a / b


def main():
    import argparse

    parser = argparse.ArgumentParser(description='Simple calculator')
    parser.add_argument('operation', choices=['add','subtract','multiply','divide'])
    parser.add_argument('x', type=float)
    parser.add_argument('y', type=float)
    args = parser.parse_args()

    ops = {
        'add': add,
        'subtract': subtract,
        'multiply': multiply,
        'divide': divide,
    }
    result = ops[args.operation](args.x, args.y)
    print(result)


if __name__ == '__main__':
    main()
'''
            return CoderOutput(content=code)

        if agent_type == AgentType.CRITIC:
            return CriticOutput(approved=True, issues=[], overall_assessment='Approved')

        if agent_type == AgentType.TESTER:
            return TesterOutput(tests_passed=1, tests_failed=0, failures=[], ready_for_review=True)

        raise RuntimeError(f'Unsupported agent type: {agent_type}')


async def main():
    db_path = Path('/tmp/demo_calculator.db')
    if db_path.exists():
        db_path.unlink()

    settings = FleetSettings()
    settings_dict = settings.model_dump()
    settings_dict['workspace']['base_path'] = '/tmp/demo_workspaces'
    settings = FleetSettings.model_validate(settings_dict)

    db = Database(db_path)
    await db.connect()
    orch = Orchestrator(db, settings)
    orch.executor = CalculatorDummyExecutor(settings)
    job_id = await orch.submit_job(goal='Build a simple calculator in python', config={'source': 'demo_calculator'})
    job = await orch.job_manager.get_job(job_id)
    ws = Path(job.workspace_path)
    calc_file = ws / 'calculator.py'
    print('JOB_ID', job_id)
    print('STATUS', job.state)
    print('WORKSPACE', ws)
    print('CALCULATOR_EXISTS', calc_file.exists())
    if calc_file.exists():
        print('CALCULATOR_CONTENT_START')
        print(calc_file.read_text())
        print('CALCULATOR_CONTENT_END')
    await db.close()


if __name__ == '__main__':
    asyncio.run(main())
